services:
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-data-planner
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - DOTNET_ENVIRONMENT=Production
    volumes:
      - bot-db:/app
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
    networks:
      - bot-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-db:
    driver: local

networks:
  bot-network:
    driver: bridge